#!/usr/bin/env bash
set -eu
mkdir -p .build/
pandoc --standalone -t slidy --css=../presentation.css \
        project-presentation.md  -o .build/presentation.html
pandoc --standalone -t latex \
        project-proposal.md  -o .build/project-proposal.pdf
