#!/usr/bin/env python3

import os
import subprocess
import sys

# Bootstrapping
# =============

# Make sure the KNinja repo is available.
#
subprocess.check_call(['git', 'submodule', 'update', '--init', '--recursive'])
extdir = 'ext'
sys.path.append(os.path.join(os.path.dirname(__file__), extdir))

from kninja import *

# Build
# =====

proj = KProject(extdir = extdir)


# Fuzzer
# ------

fuzzer = proj.definition( alias       = 'fuzzer'
                        , main        = 'fuzzer.md'
                        , backend     = 'llvm'
                        , flags       = '--gen-bison-parser --syntax-module KORE'
                        )

# Languages
# ---------

imp_haskell = proj.definition(alias = 'imp-haskell', main = 'imp/imp.md', backend = 'haskell')
imp_llvm    = proj.definition(alias = 'imp-llvm',    main = 'imp/imp.md', backend = 'llvm',     flags = '--coverage' )

proj.main()
