#!/usr/bin/env bash

echo Building ...

set -eu
cd $(dirname $0)

mkdir -p ../.build/doc
pandoc -t revealjs -s -o ../.build/doc/presentation.html presentation.md \
       -V revealjs-url=./../../doc/reveal.js-master \
       --template ./template.revealjs --css=../../doc/presentation.css

pandoc --standalone \
       --template template.tex \
       --to latex \
       --listings \
       --filter pandoc-crossref \
       --filter pandoc-citeproc \
        report.md  -o ../.build/doc/report.pdf

echo Done.
echo
echo
