#!/usr/bin/env bash
set -eu
cd $(dirname $0)

mkdir -p ../.build/doc
pandoc --standalone -t slidy --css=../../doc/presentation.css \
        project-presentation.md  -o ../.build/doc/presentation.html
pandoc --standalone -t latex \
        project-proposal.md  -o ../.build/doc/project-proposal.pdf
