#!/usr/bin/env bash
set -eu
cd $(dirname $0)

mkdir -p ../.build/doc
pandoc -t revealjs -s -o ../.build/doc/presentation.html presentation.md \
       -V revealjs-url=./../../doc/reveal.js-master \
       --template ./template.revealjs --css=../../doc/presentation.css

pandoc --standalone -t latex --template ./template.tex --listings \
        report.md  -o ../.build/doc/report.pdf
